version: '3'

tasks:
  default:
    cmds:
      - task: proto

  proto:
    desc: Build Go stub from proto
    cmds:
      - rm -rf gen/go && mkdir -p gen/go
      - find . -name "*.proto" | xargs protoc --go_opt=paths=source_relative --go_out=gen/go -I ./proto
  json:
    desc: Build Go stub from proto
    cmds:
      - rm -rf gen/jsonschema && mkdir -p gen/jsonschema
      - find . -name "*.proto" | xargs protoc --jsonschema_out=gen/jsonschema --proto_path=proto
