version: '3'

tasks:
  default:
    cmds:
      - task: generate

  generate:
    desc: Generate Go and JSON Schema from proto files
    cmds:
      - buf generate
      - task: rename-schemas

  rename-schemas:
    desc: Rename JSON schemas to simple consumer-friendly names
    dir: gen/jsonschema
    cmds:
      - |
        for f in *.jsonschema.bundle.json; do
          simple=$(echo "$f" | sed 's/.*\.\([A-Z][a-zA-Z]*\)\.jsonschema\.bundle\.json/\1.json/')
          mv "$f" "$simple"
        done

  lint:
    desc: Lint proto files
    cmds:
      - buf lint

  breaking:
    desc: Check for breaking changes against main branch
    cmds:
      - buf breaking --against '.git#branch=main'

  format:
    desc: Format proto files
    cmds:
      - buf format -w
