version: '3'

vars:
  ARTIFACT: harp-kv

tasks:
  default:
    cmds:
      - task: build

  compile:
    desc: Compile artefact
    cmds:
      - go mod vendor
      - mage compile

  test:
    desc: Test artefact
    cmds:
      - mage test

  release:
    desc: Generate a release
    cmds:
      - go mod vendor
      - mage release

  release-pack:
    desc: Generate final artefact to publish to GH
    cmds:
      - rm -rf dist && mkdir dist
      - "tar cfJ dist/{{.ARTIFACT}}-darwin-amd64-$RELEASE.tar.xz -C bin {{.ARTIFACT}}-darwin-amd64"
      - "tar cfJ dist/{{.ARTIFACT}}-linux-amd64-$RELEASE.tar.xz -C bin {{.ARTIFACT}}-linux-amd64"
      - "tar cfJ dist/{{.ARTIFACT}}-windows-amd64-$RELEASE.tar.xz -C bin {{.ARTIFACT}}-windows-amd64.exe"
      - cd dist && sha256sum {{.ARTIFACT}}-*.tar.xz > {{.ARTIFACT}}-checksum.txt
      - cd dist && gpg --detach-sign --armor {{.ARTIFACT}}-checksum.txt
      - cat dist/{{.ARTIFACT}}-checksum.txt
      - mage homebrew > dist/{{.ARTIFACT}}.rb
